## 1. Selección de variables

In [8]:
from pymongo import MongoClient
import pandas as pd

In [9]:
# Conexión MongoDB
cliente = MongoClient("mongodb://localhost:27017/")

# Base de datos
db = cliente["taller4_db"]

# Colección
coleccion = db["raw_data"]

In [10]:
# Leer documentos MongoDB
datos = list(coleccion.find())

# Ver cantidad de documentos
print(f"Total documentos: {len(datos)}")

Total documentos: 100

In [11]:
# Crear DataFrame seleccionando variables relevantes
df = pd.DataFrame(datos)[[
    "id",
    "firstName",
    "lastName",
    "fullName",
    "title",
    "family",
    "imageUrl"
]]

# Mostrar primeras filas
df.head()

,id,firstName,lastName,fullName,title,family,imageUrl
0,0,Daenerys,Targaryen,Daenerys Targaryen,Mother of Dragons,House Targaryen,https://thronesapi.com/assets/images/daenerys.jpg
1,1,Samwell,Tarly,Samwell Tarly,Maester,House Tarly,https://thronesapi.com/assets/images/sam.jpg
2,2,Jon,Snow,Jon Snow,King of the North,House Stark,https://thronesapi.com/assets/images/jon-snow.jpg
3,3,Arya,Stark,Arya Stark,No One,House Stark,https://thronesapi.com/assets/images/arya-star...
4,4,Sansa,Stark,Sansa Stark,Lady of Winterfell,House Stark,https://thronesapi.com/assets/images/sansa-sta...

## 2. Análisis exploratorio

# Inspección

In [13]:
# Primeras filas del DataFrame
df.head()

,id,firstName,lastName,fullName,title,family,imageUrl
0,0,Daenerys,Targaryen,Daenerys Targaryen,Mother of Dragons,House Targaryen,https://thronesapi.com/assets/images/daenerys.jpg
1,1,Samwell,Tarly,Samwell Tarly,Maester,House Tarly,https://thronesapi.com/assets/images/sam.jpg
2,2,Jon,Snow,Jon Snow,King of the North,House Stark,https://thronesapi.com/assets/images/jon-snow.jpg
3,3,Arya,Stark,Arya Stark,No One,House Stark,https://thronesapi.com/assets/images/arya-star...
4,4,Sansa,Stark,Sansa Stark,Lady of Winterfell,House Stark,https://thronesapi.com/assets/images/sansa-sta...

In [14]:
# Información general del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         100 non-null    int64
 1   firstName  100 non-null    object
 2   lastName   100 non-null    object
 3   fullName   100 non-null    object
 4   title      100 non-null    object
 5   family     100 non-null    object
 6   imageUrl   100 non-null    object
dtypes: int64(1), object(6)
memory usage: 5.6+ KB

In [15]:
# Verificar valores nulos
df.isnull().sum()

id           0
firstName    0
lastName     0
fullName     0
title        0
family       0
imageUrl     0
dtype: int64

In [16]:
# Estadísticas descriptivas
df.describe(include="all")

,id,firstName,lastName,fullName,title,family,imageUrl
count,100.000000,100,100,100,100,100,100
unique,NaN,52,31,52,49,35,53
top,NaN,Robert,Stark,Robert Baratheon,Lord of Winterfell,House Stark,https://thronesapi.com/assets/images/daenerys.jpg
freq,NaN,4,16,4,6,14,2
mean,24.590000,NaN,NaN,NaN,NaN,NaN,NaN
std,14.659154,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,12.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,24.500000,NaN,NaN,NaN,NaN,NaN,NaN
75%,37.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,52.000000,NaN,NaN,NaN,NaN,NaN,NaN

# Insights numericos

In [17]:
# Total de personajes
print("Total personajes:", df.shape[0])

Total personajes: 100

In [18]:
# Familias únicas
print("Cantidad de familias únicas:", df["family"].nunique())

Cantidad de familias únicas: 35

In [19]:
# Familia con más personajes
print(df["family"].value_counts().head(1))

family
House Stark    14
Name: count, dtype: int64

In [20]:
# Longitud del título
df["longitud_title"] = df["title"].astype(str).apply(len)

personaje_titulo_largo = df.loc[df["longitud_title"].idxmax()]

print("Personaje con el título más largo:")
print(personaje_titulo_largo["fullName"])
print(personaje_titulo_largo["title"])

Personaje con el título más largo:
Joffrey Baratheon
Lord of the Seven Kingdoms, Protector of the Realm

In [21]:
# Promedio longitud nombres completos
df["longitud_nombre"] = df["fullName"].apply(len)

print(
    "Promedio longitud nombres:",
    round(df["longitud_nombre"].mean(), 2)
)

Promedio longitud nombres: 12.24